# Generated by Django 5.0.4 on 2024-05-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petittion',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='petittion',
            name='passport_series',
        ),
    ]
