# Generated by Django 5.0.4 on 2024-04-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='expire_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
