# Generated by Django 5.0.4 on 2024-04-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_needhelp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('donater', 'Donater')], default='donater', max_length=100),
        ),
    ]
