# Generated by Django 5.0.4 on 2024-04-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_needhelp_file_needhelp_let_needhelp_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needhelp',
            old_name='let',
            new_name='locations',
        ),
        migrations.RemoveField(
            model_name='needhelp',
            name='log',
        ),
    ]
